# Numpy Functions Tutorials

In [1]:
import numpy as np

In [24]:
# zeros 
zero_arr = np.zeros([1,3], dtype="int" )
print(type(zero_arr[0,0]))
zero_arr


<class 'numpy.int32'>


array([[0, 0, 0]])

In [18]:
# onces functions
one_arr=np.ones([3,3])
print(one_arr)
print(type(one_arr[0,0]))

one_arr=np.ones([3,3], dtype="int") #type change, default type is float64  
print(one_arr)
print(type(one_arr[0,0]))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
<class 'numpy.float64'>
[[1 1 1]
 [1 1 1]
 [1 1 1]]
<class 'numpy.int32'>


In [28]:
# empty function
empty_arr=np.empty(2)
print(empty_arr)
print(type(empty_arr[0]))

[4.53619290e+287 7.28932266e-094]
<class 'numpy.float64'>


In [69]:
#randam function
print(" 1-D")
randam_arr= np.random.rand(3)
print(randam_arr)
print(" ")
print(" 2-D")
randam_arr= np.random.rand(3,2)
print(randam_arr)

randam_arr= np.random.rand(3,2, 2)
print(" ")
print("3-D")
print(randam_arr)

 1-D
[0.29424012 0.18663643 0.86051074]
 
 2-D
[[0.5286027  0.44384957]
 [0.49582222 0.5448674 ]
 [0.81919744 0.94005276]]
 
3-D
[[[0.36939618 0.17643683]
  [0.10645281 0.82550174]]

 [[0.99848495 0.62180888]
  [0.09482009 0.6742527 ]]

 [[0.86552426 0.50641229]
  [0.04083505 0.38452177]]]


In [47]:
randama_arr=np.random.randn(2,4)
print(randama_arr)

[[ 0.63969159 -2.75624578 -0.00656109  0.88465678]
 [-0.75065773 -1.0625018  -0.59939336  0.67831879]]


In [70]:
print(np.arange(10,30,5))

print(np.linspace(10,20,9))

[10 15 20 25]
[10.   11.25 12.5  13.75 15.   16.25 17.5  18.75 20.  ]


# numpy array with array ()

In [52]:
import numpy as np

np.array([10,20,30,40])

variable =[50,60,70,8.9]

print(type(variable[0]))

print(type(variable[3]))


<class 'int'>
<class 'float'>


#numpy array with the zero() function

In [60]:
import numpy as np

zeroarr=np.zeros(4)
print(zeroarr)
print(type(zeroarr[2]))

[0. 0. 0. 0.]
<class 'numpy.float64'>


In [63]:
import numpy as np

zeroarr=np.zeros(4, dtype="int")
print(zeroarr)
print(type(zeroarr[2]))

[0 0 0 0]
<class 'numpy.int32'>


In [68]:
import numpy as np

zeroarr=np.zeros((4,4), dtype="int")
print(zeroarr)
print(type(zeroarr[2,3]))

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
<class 'numpy.int32'>


### <center>*ones() function in numpy*</center>

In [73]:
import numpy as np
onesfun=np.ones(5)
print(onesfun)

[1. 1. 1. 1. 1.]


In [77]:
np.ones([ 3, 3]) 

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [89]:
import numpy as np


arrange_array=np.arange(3,9,2)
print(arrange_array)



[3 5 7]
