# <center>Numpy Tutorials</center>

1. NumPy is a Python library used for working with arrays.
2. NumPy stands for Numerical Python.

In [5]:
import numpy as np

arr = np.array((1, 2, 3, 4, 5))

print(arr)

[1 2 3 4 5]


### <center>*0-D Arrays*</center>

In [6]:
import numpy as np

arr = np.array(42)

print(arr)



42


In [10]:
import numpy as np

arr = np.array(55)

print(arr)
print(arr.shape)
print(arr.ndim)

55
()
0


### <center>*1-D Arrays*</center>

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)
print("first five element", arr[:3])

[1 2 3 4 5]
first five element [1 2 3]


In [15]:
import numpy as np

arr = np.array([4,5,6,7])

print(arr)
print(arr.shape)
print(arr.ndim)

[4 5 6 7]
(4,)
1


### <center>*2-D Arrays*</center>

In [ ]:
import numpy as np

arr = np.array([[1, 2,3 ], [4, 5, 6], [30, 40, 50]])

print(arr)
print("first five element", arr[0, :2])

[[ 1  2  3]
 [ 4  5  6]
 [30 40 50]]
first five element [1 2]


In [28]:
import numpy as np

arr = np.array([[7,8,9],[10,11,12],[13,14,15]])

print(arr)
print(arr.shape)
print(arr.ndim)
print(arr[1][0])

[[ 7  8  9]
 [10 11 12]
 [13 14 15]]
(3, 3)
2
10


### <center>*3-D Arrays*</center>

In [ ]:
import numpy as np

arr = np.array([[[1, 2,3], [4, 5,6]], [[10, 2, 3], [4, 5, 6]]])

#print(arr)
arr.shape
print("element of array", arr)
#print("first five element", arr[0, 1, :2])


element of array [[[ 1  2  3]
  [ 4  5  6]]

 [[10  2  3]
  [ 4  5  6]]]


In [33]:
import numpy as np

arr=np.array([[[2,3,4],[5,6,7],[8,9,10],[1,2,3]], [[20,30,40],[50,60,70],[80,90,10],[11,20,30]]])

print(arr)
print(arr.shape)
print(arr.ndim)
print(arr[0][1][1])
print(arr[1][2][0])

[[[ 2  3  4]
  [ 5  6  7]
  [ 8  9 10]
  [ 1  2  3]]

 [[20 30 40]
  [50 60 70]
  [80 90 10]
  [11 20 30]]]
(2, 4, 3)
3
6
80


### <center>* n-D Arrays*</center>

In [ ]:
import numpy as np

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3
